routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\MarkController;
use App\Http\Controllers\ArticleGuestController;
use App\Http\Controllers\AdminManageUsers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','App\Http\Controllers\HomeController@index');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('introduction', function () { return view('introduction'); })->name("introduction");
Route::group(['middleware' => 'auth2'], function () {     
    Route::get('user', function () { return view('user'); })->name("user");
    Route::get('admin', function () { return view('admin'); })->name("admin");
    //Route::get('/test1', function () { return view('test1'); })->name('test1');
    Route::resource('adminpanel', AdminManageUsers::class); 
    //Route::get('adminpanel', [AdminManageUsers::class, 'adminpanel'])->name('adminpanel');
    //Route::get('adminpanel/{admin}',[AdminManageUser::class,'show'])->name('adminpanel.show');
    Route::get('/test2', function () { return view('test2'); })->name('test2'); 
    Route::resource('articles', ArticleController::class);
    Route::view('/addtostudents','addtostudents');
    Route::put('/addtostudents','App\Http\Controllers\Studentcontroller@addtostudents');
    Route::view('/addtosubjects','addtosubjects');
    Route::put('/addtosubjects','App\Http\Controllers\Subjectcontroller@addtosubjects');
    Route::view('/addtomarks','addtomarks');
    Route::put('/addtomarks','App\Http\Controllers\Markcontroller@addtomarks');
    Route::view('/addto','addto');
    Route::view('/getdata','getdata');
    Route::get('/getstudents','App\Http\Controllers\Studentcontroller@getstudents');
    Route::get('/getmarks','App\Http\Controllers\Markcontroller@getmarks');
    Route::get('/getsubjects','App\Http\Controllers\Subjectcontroller@getsubjects');
    
});
//Route::resource('adminpanel', AdminManageUsers::class); 
Route::resource('articlesguest', ArticleGuestController::class);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/addto.blade.php
@extends('layout')

@section('content')
<style>
    h1{
        color:black;
        text-align:center;
    }
    #padding{
        padding-bottom:150px;
        
    }
    #infos{
        text-align:center;
    }
    #a{
        color:black;
        font-size:30px;
    }
</style>
<h1>Which table do you want to add data to?</h1>
<div>
    <ul id="padding"></ul>
<div id="infos">
<a id="a" href="/addtomarks"> Add to marks </a>
</div>
<ul id="padding"></ul>
<div id="infos">
<a id="a" href="/addtosubjects"> Add to subjects </a>
</div>
<ul id="padding"></ul>
<div id="infos">
<a id="a" href="/addtostudents"> Add to students </a>
</div>
</div>
@stop

resources/views/addtosubjects.blade.php
@extends('layout')

@section('content')
@if($errors->any())
<style>
  .danger{
    color: red;
    font-size:24px;
  }
</style>
<ul>
  @foreach($errors->all() as $error)
  <li class="danger">{{$error}}</li>
  @endforeach
</ul>
@endif
<style>
  h1,label{
    color:black;
  }
</style>
<h1>Add to users table</h1>
<div class="col-sm-6">
<form action="" method="post">
    @csrf
    {{ method_field('PUT')}}
  <div class="form-group">
    <label>Subject name:</label>
    <input type="" class="form-control" id="sname" name="sname" placeholder="Enter your subject's name" required>
  </div>
  <div class="form-group">
    <label>Subject category</label>
    <input type="" class="form-control" id="caregory" name="category" placeholder="Enter your subject's category" required>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
@stop

resources/views/admin.blade.php
<?php $header = "Admin page header";?>
<x-app-layout>
    <x-slot name="header">
        {{ $header }}
    </x-slot>
    <h1>Admin page: visible only to admin</h1>
</x-app-layout>

resources/views/adminpanel.blade.php
@extends('layout')
@extends('layouts.app2')

@section('content')
<?php if (Auth::user()->role==1){?>
    <p><strong>The admin panel is ready!</strong></p>
<h2>Bootstrap table</h2>
<div class="row mb-4">
    <div class="col-xl-6">
        @if(Session::has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('success')}}
            </div>
        @endif
        @if(Session::has('failed'))
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('failed')}}
            </div>
        @endif 
    </div>
</div>
<table class="table table-striped">
    <thead>
        <th> Id </th>
        <th> Name </th>
        <th> Email </th>
        <th> Role </th>
    </thead>
    <tbody>
            @foreach($admin as $adm)
                <tr>
                    <td> {{$adm->id}} </td>
                    <td> {{$adm->name}} </td>
                    <td> {{$adm->email}} </td>
                    <td> {{$adm->role}} </td>
                    <td>
                        <form action="{{route('adminpanel.destroy', $adm->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('adminpanel.show', $adm->id)}}" class="btn btn-sm btn-info"> View </a>
                            <a href="{{route('adminpanel.edit', $adm->id)}}" class="btn btn-sm btn-success"> Edit </a>
                            <button type="submit" class="btn btn-sm btn-danger"> Delete </button>
                        </form>
                    </td>
                </tr>
            @endforeach
    </tbody>
</table>

                        <?php } ?> 

@endsection

resources/views/articles.blade.php
@extends("layout")
@section("title") Articles @endsection
@section("content")
<style>
    h1,table{
        color:black;
    }
    #button{
        padding-top:15px;
    }
</style>
<div class="row mb-4">
    <div class="col-xl-6">
        @if(Session::has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('success')}}
            </div>
        @endif
        @if(Session::has('failed'))
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('failed')}}
            </div>
        @endif 
    </div>
    <div id="button" class="col-xl-6 text-right">
        <a href="{{route('articles.create')}}" class="btn btn-success "> Add New </a>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <th> Id </th>
        <th> Title </th>
        <th> Description </th>
        <th> Action </th>
    </thead>
    <tbody>
        @if(count($articles) > 0)
            @foreach($articles as $article)
                <tr>
                    <td> {{$article->id}} </td>
                    <td> {{$article->title}} </td>
                    <td> {{$article->description}} </td>
                    <td>
                        <form action="{{route('articles.destroy', $article->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('articles.show', $article->id)}}" class="btn btn-sm btn-info"> View </a>
                            <a href="{{route('articles.edit', $article->id)}}" class="btn btn-sm btn-success"> Edit </a>
                            <button type="submit" class="btn btn-sm btn-danger"> Delete </button>
                        </form>
                        
                    </td>
                </tr>
            @endforeach
        @endif
    </tbody>
</table>
{!! $articles->links() !!}
@endsection

resources/views/articlesguest.blade.php
@extends("layout")
@section("title") Articles @endsection
@section("content")
<style>
    h1,table{
        color:black;
    }
    #button{
        padding-top:15px;
    }
</style>
<div class="row mb-4">
    <div class="col-xl-6">
        @if(Session::has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('success')}}
            </div>
        @endif
        @if(Session::has('failed'))
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">× </button>
                {{Session::get('failed')}}
            </div>
        @endif 
    </div>
    <div id="button" class="col-xl-6 text-right">
        <a href="{{route('articles.create')}}" class="btn btn-success "> Add New </a>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <th> Id </th>
        <th> Title </th>
        <th> Description </th>
        <th> Action </th>
    </thead>
    <tbody>
        @if(count($articles) > 0)
            @foreach($articles as $article)
                <tr>
                    <td> {{$article->id}} </td>
                    <td> {{$article->title}} </td>
                    <td> {{$article->description}} </td>
                    <td>
                    
                    </td>
                </tr>
            @endforeach
        @endif
    </tbody>
</table>
{!! $articles->links() !!}
@endsection

resources/views/create-article.blade.php
@extends("layout")
@section("title") Create Article @endsection
@section("content")
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 text-right">
            <a href="{{route('articles.index')}}" class="btn btn-danger"> Back to Articles </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 m-auto">
                <form action="{{route('articles.store')}}" method="POST">
                @csrf
                <div class="card shadow">
                    @if(Session::has('success'))
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert">× </button>
                            {{Session::get('success')}}
                        </div>
                    @elseif(Session::has('failed'))
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert">× </button>
                            {{Session::get('failed')}}
                        </div>
                    @endif
                    <div class="card-header">
                        <h4 class="card-title"> Create Article </h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title"> Title </label>
                            <input type="text" name="title" class="form-control" id="title" value="{{old('title')}}">
                            {!!$errors->first("title", "<span class='text-danger'>:message </span>")!!}
                        </div>
                        <div class="form-group">
                            <label for="description"> Description </label>
                            <textarea class="form-control" name="description" id="description">{{old('description')}}</textarea>
                            {!!$errors->first("description", "<span class='text-danger'>:message </span>") !!}
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success"> Save </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/getdata.blade.php
@extends('layout')

@section('content')
<style>
  h1,label{
    color:black;
  }
</style>
<h1>What table do you want to see?</h1>
<div class="col-sm-6">
<form>
    <div class="form-group">
    <label>Database you want to see</label>
    <input type="text" class="form-control" id="class" name="class" required>
  </div>
  <button id="submit" onClick="myOnclickFn()" type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
<script>
    function myOnClickFn(){
        document.location.href="";
    }

</script>
@stop

resources/views/introduction.blade.php
<?php $header = "Introduction page header";?>
<x-app-layout>
    <x-slot name="header">
        {{ $header }}
    </x-slot>
    <h1>Introduction page: visible to all users</h1>
</x-app-layout>

resources/views/layout.blade.php
<style>
  .footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  text-align: center;
  color:black;
}
  body{
    background-image:url("https://www.wallpapers4u.org/wp-content/uploads/clipart_room_board_pointer_students_teachers_knowledge_19533_1920x1080.jpg");
    background-repeat: repeat;
  }
}
</style>
<html>
    <head>
        <title>
            Student managing site
        </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Student managing site</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/adminpanel">Adminpanel</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articlesguest">Articles for guests</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/articles">Articles for users</a>
      </li>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/addto">Add to database</a>
      </li>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/getdata">Get table</a>
      </li>
    </ul>
  </div>
  <div class="relative flex items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0">
            @if (Route::has('login'))
                <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
                    @auth
                        <a href="{{ url('/dashboard') }}" class="text-sm text-gray-700 dark:text-gray-500 underline">Dashboard</a>
                    @else
                        <a href="{{ route('login') }}" class="text-sm text-gray-700 dark:text-gray-500 underline">Log in</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 dark:text-gray-500 underline">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

        </div>
</nav>
        <div class="container">
            @yield('content')
        </div>
        <div class="footer">
        <footer>
            Copyright by Student managing
        </footer>
        </div>
    </body>
</html>

resources/views/show-article.blade.php
@extends("layout")
@section("title") Show Article @endsection
@section("content")
<style>
  #cardheader{
    color:black;
  }
</style>
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 text-right">
            <a href="{{route('articles.index')}}" class="btn btn-danger"> Back to Articles </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 m-auto">
            <div class="card shadow">
                <div class="card-header">
                    <h4 class="card-title"> Show Article </h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title"> Title </label>
                        <input type="text" readonly name="title" class="form-control" id="title" value="@if(!empty($article)) {{$article->title}} @endif">
                    </div>
                    <div class="form-group">
                        <label for="description"> Description </label>
                        <textarea class="form-control" readonly name="description" id="description">@if(!empty($article)) {{$article->description}} @endif</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/show-user.blade.php
@extends("layout")
@section("title") Show User @endsection
@section("content")
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 text-right">
            <a href="{{route('adminpanel.index')}}" class="btn btn-danger"> Back to AdminPanel </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 m-auto">
            <div class="card shadow">
                <div class="card-header">
                    <h4 class="card-title"> Show User </h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="title"> Name </label>
                        <input type="text" readonly name="Name" class="form-control" id="name" value="@if(!empty($user)) {{$user->name}} @endif">
                    </div>
                    <div class="form-group">
                        <label for="description"> Email </label>
                        <textarea class="form-control" readonly name="email" id="email">@if(!empty($user)) {{$user->email}} @endif</textarea>
                    </div>
                    <div class="form-group">
                        <label for="description"> Role </label>
                        <textarea class="form-control" readonly name="role" id="role">@if(!empty($user)) {{$user->role}} @endif</textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user.blade.php
<?php $header = "User page header";?>
<x-app-layout>
    <x-slot name="header">
        {{ $header }}
    </x-slot>
    <h1>User page: visible to logged in users</h1>
</x-app-layout>

resources/views/view1.blade.php
<?php
if (!Auth::check()) echo "Not logged in";
else{
    echo "Logged in<br>";
    echo "ID: ".Auth::user()->id."<br>";
    echo "Name: ".Auth::user()->name."<br>";
    echo "Email: ".Auth::user()->email."<br>";
}